theme: jekyll-theme-minimal
title: Welcome to Timmy's Art Hum Journal!
description: 2018 Spring Art Humanities, taught by Dr. Caroline A. Wamsler! 

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
